name: Deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - '.editorconfig'
      - 'package.json'
      - 'README.md'
      - 'LICENSE'
      - '.wp-env.js'

  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Build block
      run: |
        npm install
        npm run build --if-present

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: wp-content/plugins/comment-avatars-block/
        protocol: sftp
        port: 22
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          README.md
          package.json
          composer.json
          package-lock.json
          .wp-env.json
          .wp-env-generator.json
